import os
import time
os.system ('clear')
print '\t _                 _'
print '\t| |__   __ _ _ __ (_)'
print '\t|  _ \ / _` |  _ \| |'
print '\t| | | | (_| | | | | |'
print '\t|_| |_|\__,_|_| |_|_|'
print '\t      _       _'
print '\t  ___(_)_ __ | |_ __ _'
print '\t / __| |  _ \| __/ _` |'
print '\t| (__| | | | | || (_| |'
print '\t \___|_|_| |_|\__\__,_|' 
print '\t     _               _'
print '\t  __| | _____      _(_)'
print '\t / _` |/ _ \ \ /\ / / |'
print '\t| (_| |  __/\ V  V /| |'
print '\t \__,_|\___| \_/\_/ |_|'
time.sleep(1)
print '\t _                 _'
print '\t| |__   __ _ _ __ (_)'
print '\t|  _ \ / _` |  _ \| |'
print '\t| | | | (_| | | | | |'
print '\t|_| |_|\__,_|_| |_|_|'
print '\t      _       _'
print '\t  ___(_)_ __ | |_ __ _'
print '\t / __| |  _ \| __/ _` |'
print '\t| (__| | | | | || (_| |'
print '\t \___|_|_| |_|\__\__,_|' 
print '\t     _               _'
print '\t  __| | _____      _(_)'
print '\t / _` |/ _ \ \ /\ / / |'
print '\t| (_| |  __/\ V  V /| |'
print '\t \__,_|\___| \_/\_/ |_|'
time.sleep(1)
print '\t _                 _'
print '\t| |__   __ _ _ __ (_)'
print '\t|  _ \ / _` |  _ \| |'
print '\t| | | | (_| | | | | |'
print '\t|_| |_|\__,_|_| |_|_|'
print '\t      _       _'
print '\t  ___(_)_ __ | |_ __ _'
print '\t / __| |  _ \| __/ _` |'
print '\t| (__| | | | | || (_| |'
print '\t \___|_|_| |_|\__\__,_|' 
print '\t     _               _'
print '\t  __| | _____      _(_)'
print '\t / _` |/ _ \ \ /\ / / |'
print '\t| (_| |  __/\ V  V /| |'
print '\t \__,_|\___| \_/\_/ |_|'
time.sleep(1)
print '\t _                 _'
print '\t| |__   __ _ _ __ (_)'
print '\t|  _ \ / _` |  _ \| |'
print '\t| | | | (_| | | | | |'
print '\t|_| |_|\__,_|_| |_|_|'
print '\t      _       _'
print '\t  ___(_)_ __ | |_ __ _'
print '\t / __| |  _ \| __/ _` |'
print '\t| (__| | | | | || (_| |'
print '\t \___|_|_| |_|\__\__,_|' 
print '\t     _               _'
print '\t  __| | _____      _(_)'
print '\t / _` |/ _ \ \ /\ / / |'
print '\t| (_| |  __/\ V  V /| |'
print '\t \__,_|\___| \_/\_/ |_|'
time.sleep(1)
print '\t _                 _'
print '\t| |__   __ _ _ __ (_)'
print '\t|  _ \ / _` |  _ \| |'
print '\t| | | | (_| | | | | |'
print '\t|_| |_|\__,_|_| |_|_|'
print '\t      _       _'
print '\t  ___(_)_ __ | |_ __ _'
print '\t / __| |  _ \| __/ _` |'
print '\t| (__| | | | | || (_| |'
print '\t \___|_|_| |_|\__\__,_|' 
print '\t     _               _'
print '\t  __| | _____      _(_)'
print '\t / _` |/ _ \ \ /\ / / |'
print '\t| (_| |  __/\ V  V /| |'
print '\t \__,_|\___| \_/\_/ |_|'
time.sleep(1)
print '\t _                 _'
print '\t| |__   __ _ _ __ (_)'
print '\t|  _ \ / _` |  _ \| |'
print '\t| | | | (_| | | | | |'
print '\t|_| |_|\__,_|_| |_|_|'
print '\t      _       _'
print '\t  ___(_)_ __ | |_ __ _'
print '\t / __| |  _ \| __/ _` |'
print '\t| (__| | | | | || (_| |'
print '\t \___|_|_| |_|\__\__,_|' 
print '\t     _               _'
print '\t  __| | _____      _(_)'
print '\t / _` |/ _ \ \ /\ / / |'
print '\t| (_| |  __/\ V  V /| |'
print '\t \__,_|\___| \_/\_/ |_|'
time.sleep(1)
print '\t _                 _'
print '\t| |__   __ _ _ __ (_)'
print '\t|  _ \ / _` |  _ \| |'
print '\t| | | | (_| | | | | |'
print '\t|_| |_|\__,_|_| |_|_|'
print '\t      _       _'
print '\t  ___(_)_ __ | |_ __ _'
print '\t / __| |  _ \| __/ _` |'
print '\t| (__| | | | | || (_| |'
print '\t \___|_|_| |_|\__\__,_|' 
print '\t     _               _'
print '\t  __| | _____      _(_)'
print '\t / _` |/ _ \ \ /\ / / |'
print '\t| (_| |  __/\ V  V /| |'
print '\t \__,_|\___| \_/\_/ |_|'
time.sleep(1)
print '\t _                 _'
print '\t| |__   __ _ _ __ (_)'
print '\t|  _ \ / _` |  _ \| |'
print '\t| | | | (_| | | | | |'
print '\t|_| |_|\__,_|_| |_|_|'
print '\t      _       _'
print '\t  ___(_)_ __ | |_ __ _'
print '\t / __| |  _ \| __/ _` |'
print '\t| (__| | | | | || (_| |'
print '\t \___|_|_| |_|\__\__,_|' 
print '\t     _               _'
print '\t  __| | _____      _(_)'
print '\t / _` |/ _ \ \ /\ / / |'
print '\t| (_| |  __/\ V  V /| |'
print '\t \__,_|\___| \_/\_/ |_|'
time.sleep(1)
print '\t _                 _'
print '\t| |__   __ _ _ __ (_)'
print '\t|  _ \ / _` |  _ \| |'
print '\t| | | | (_| | | | | |'
print '\t|_| |_|\__,_|_| |_|_|'
print '\t      _       _'
print '\t  ___(_)_ __ | |_ __ _'
print '\t / __| |  _ \| __/ _` |'
print '\t| (__| | | | | || (_| |'
print '\t \___|_|_| |_|\__\__,_|' 
print '\t     _               _'
print '\t  __| | _____      _(_)'
print '\t / _` |/ _ \ \ /\ / / |'
print '\t| (_| |  __/\ V  V /| |'
print '\t \__,_|\___| \_/\_/ |_|'
time.sleep(1)
print '\t _                 _'
print '\t| |__   __ _ _ __ (_)'
print '\t|  _ \ / _` |  _ \| |'
print '\t| | | | (_| | | | | |'
print '\t|_| |_|\__,_|_| |_|_|'
print '\t      _       _'
print '\t  ___(_)_ __ | |_ __ _'
print '\t / __| |  _ \| __/ _` |'
print '\t| (__| | | | | || (_| |'
print '\t \___|_|_| |_|\__\__,_|' 
print '\t     _               _'
print '\t  __| | _____      _(_)'
print '\t / _` |/ _ \ \ /\ / / |'
print '\t| (_| |  __/\ V  V /| |'
print '\t \__,_|\___| \_/\_/ |_|'
time.sleep(1)
print '\t _                 _'
print '\t| |__   __ _ _ __ (_)'
print '\t|  _ \ / _` |  _ \| |'
print '\t| | | | (_| | | | | |'
print '\t|_| |_|\__,_|_| |_|_|'
print '\t      _       _'
print '\t  ___(_)_ __ | |_ __ _'
print '\t / __| |  _ \| __/ _` |'
print '\t| (__| | | | | || (_| |'
print '\t \___|_|_| |_|\__\__,_|' 
print '\t     _               _'
print '\t  __| | _____      _(_)'
print '\t / _` |/ _ \ \ /\ / / |'
print '\t| (_| |  __/\ V  V /| |'
print '\t \__,_|\___| \_/\_/ |_|'
time.sleep(1)
print '\t _                 _'
print '\t| |__   __ _ _ __ (_)'
print '\t|  _ \ / _` |  _ \| |'
print '\t| | | | (_| | | | | |'
print '\t|_| |_|\__,_|_| |_|_|'
print '\t      _       _'
print '\t  ___(_)_ __ | |_ __ _'
print '\t / __| |  _ \| __/ _` |'
print '\t| (__| | | | | || (_| |'
print '\t \___|_|_| |_|\__\__,_|' 
print '\t     _               _'
print '\t  __| | _____      _(_)'
print '\t / _` |/ _ \ \ /\ / / |'
print '\t| (_| |  __/\ V  V /| |'
print '\t \__,_|\___| \_/\_/ |_|'
time.sleep(1)